FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    gnupg \
    npm \
    && rm -rf /var/lib/apt/lists/*

# Install AWS CLI & CDK
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && npm install -g aws-cdk

WORKDIR /workspace
